language: php
php:
  - 5.5
  - 5.6
  - 7.0

before_script:
  - composer install --no-interaction
  
script:
  - vendor/bin/phpunit
  
deploy:
  provider: pages
  skip-cleanup: true
  github-token: $GITHUB_TOKEN
  on:
    branch: gh-pages
  
  
